routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', [\App\Http\Controllers\Site\MainController::class, 'index'])->name('main');
Route::prefix('catalog')
    ->controller(\App\Http\Controllers\Site\CatalogController::class)
    ->name('catalog.')
    ->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/{id}', 'show')->name('show');
        Route::get('filter', 'filter')->name('filter');
    });

Route::prefix('login')
    ->controller(\App\Http\Controllers\Auth\LoginController::class)
    ->name('login.')
    ->group(function () {
        Route::get('/', 'index')->name('index');
        Route::post('/store', 'store')->name('store');
    });

Route::prefix('register')
    ->controller(\App\Http\Controllers\Auth\RegisterController::class)
    ->name('register.')
    ->group(function () {
        Route::post('/store', 'store')->name('store');
    });

Route::prefix('user')
    ->name('user.')
    ->middleware('user')
    ->group(function () {
        Route::get('/', [\App\Http\Controllers\User\UserController::class, 'index'])->name('index');
        Route::post('/{id}/update', [\App\Http\Controllers\User\UserController::class, 'update'])->name('update');
        Route::get('/logout', [\App\Http\Controllers\User\UserController::class, 'logout'])->name('logout');
        Route::post('/add-adress', [\App\Http\Controllers\User\UserController::class, 'createAdress'])->name('add-adress');
        Route::post('/review', [\App\Http\Controllers\User\UserController::class, 'review'])->name('review.store');
        Route::delete('/address/{id}', [\App\Http\Controllers\User\UserController::class, 'deleteAdress'])->name('address.delete');
    });

Route::prefix('busket')
    ->name('busket.')
    ->controller(\App\Http\Controllers\Site\BusketController::class)
    ->group(function () {
        Route::get('/', 'index')->name('index');
        Route::post('/add-product', 'addProduct')->name('add-product');
        Route::post('/add-order', 'addOrder')->name('add-order');
        Route::post('delete/order', 'delete')->name('delete-order');
    });

Route::prefix('admin')
    ->name('admin.')
    ->middleware('admin')
    ->group(function () {
       Route::get('/', [\App\Http\Controllers\Admin\AdminController::class, 'index'])->name('index');
       Route::post('/product/store', [\App\Http\Controllers\Admin\ProductController::class, 'store'])->name('product.store');
       Route::get('/logout', [\App\Http\Controllers\Admin\AdminController::class, 'logout'])->name('logout');
       Route::post('/store/shoe-size', [\App\Http\Controllers\Admin\ShoeSizeController::class, 'store'])->name('shoe-size.store');
       Route::post('/store/color', [\App\Http\Controllers\Admin\ColorController::class, 'store'])->name('color.store');
       Route::post('/blog/store', [\App\Http\Controllers\Admin\BlogController::class, 'store'])->name('blog.store');
       Route::delete('/user/{id}', [\App\Http\Controllers\Admin\AdminController::class, 'deleteUser'])->name('user.delete');
       Route::delete('/product/{id}/delete', [\App\Http\Controllers\Admin\ProductController::class, 'delete'])->name('product.delete');
       Route::delete('/delete/review/{id}', [\App\Http\Controllers\Admin\ReviewController::class, 'delete'])->name('review.delete');
       Route::post('/promocode/store', [\App\Http\Controllers\Admin\PromocodeController::class, 'store'])->name('promocode.store');
       Route::delete('/promocode/delete/{id}', [\App\Http\Controllers\Admin\PromocodeController::class, 'delete'])->name('promocode.delete');
       Route::delete('/blog/delete/{id}', [\App\Http\Controllers\Admin\BlogController::class, 'delete'])->name('blog.delete');
       Route::post('answer/{id}', [\App\Http\Controllers\Admin\ContactController::class, 'store'])->name('answer.store');
       Route::patch('/update/blog/{id}', [\App\Http\Controllers\Admin\BlogController::class, 'update'])->name('blog.update');
       Route::put('/order/update/{id}', [\App\Http\Controllers\Admin\OrderController::class, 'update'])->name('order.update');
       Route::put('/product/{id}/update', [\App\Http\Controllers\Admin\ProductController::class, 'update'])->name('product.update');
    });

Route::prefix('contact')
    ->name('contact.')
    ->controller(\App\Http\Controllers\Site\ContactController::class)
    ->group(function () {
        Route::get('/', 'index')->name('index');
        Route::post('/store', 'store')->name('store');
    });

Route::view('/information', 'site.information.information')->name('information');
Route::view('/blog', 'site.blog.blog')->name('blog');
Route::get('/blog', [\App\Http\Controllers\BlogController::class, 'index'])->name('blog');

app/Http/Controllers/Site/BusketController.php
<?php

namespace App\Http\Controllers\Site;

use App\Enum\Order\StatusEnum;
use App\Http\Controllers\Controller;
use App\Models\Adress;
use App\Models\Contact;
use App\Models\Order;
use App\Models\Product;
use App\Models\Promocode;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Date;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Session;

class BusketController extends Controller
{
    public function index(): \Illuminate\Contracts\View\View|\Illuminate\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\Foundation\Application
    {
        return view('site.busket.index', [
            'carts' => Session::get('carts'),
            'adreses' => Adress::query()->where('user_id', '=', Auth::id())->get()
        ]);
    }

    public function addProduct(Request $request)
    {
        if (auth()->check()) {
            Session::start();
            $carts = Session::get('carts');
            $product = Product::query()->find($request->product_id);
            if ($product->count() != 0) {
                if (isset($carts[$product->id])) {
                    $count = $carts[$product->id]['count'] + 1;
                    $carts[$product->id] = [
                        'product_id' => $product->id,
                        'user_id' => $request->user_id,
                        'brand' => $product->brand,
                        'model' => $product->model,
                        'count' => $count,
                        'price' => $product->price * $count,
                        'description' => $product->description
                    ];
                } else {
                    $carts[$product->id] = [
                        'product_id' => $product->id,
                        'user_id' => $request->user_id,
                        'brand' => $product->brand,
                        'model' => $product->model,
                        'count' => 1,
                        'price' => $product->price,
                        'description' => $product->description
                    ];
                }
                Session::put('carts', $carts);
                Session::save();

                return response()->json([
                    'success' => true,
                    'data' => route('busket.index'),
                ], 200);
            }
        }
        return response()->json([
            'success' => false,
            'data' => 'Для покупки товаров, вам нужно авторизоваться или зарегистрироваться'
        ], 200);
    }

    public function addOrder (Request $request)
    {
        if (empty($request->code)) {
            return  redirect()->back()->with('Промокод пустой');
        }

        $promocode = Promocode::query()->where('code', '=', $request->code)->first();

        if (empty($promocode)) {
            return redirect()->back()->with('Такого промокода не существует');
        }

        foreach (Session::get('carts') as $item) {

            $product = Product::query()->find($item['product_id']);

            if ($product->count >= $item['count']) {
                $product->update([
                    'count' => $product->count - $item['count']
                ]);
            } else {
                return redirect()->back()->with('Нет количества товара');
            }

            Order::query()->create([
                'product_id' => $item['product_id'],
                'promocode_id' => $promocode->id,
                'user_id' => Auth::id(),
                'count' => $item['count'],
                'sum' => $item['price'] - $promocode->discount,
                'time' => Date::now(),
                'status' => StatusEnum::NEW->value,
                'adress_id' => $request->adress_id
            ]);
        }

        Mail::send('admin.verification.busket', ['carts' => Session::get('carts')],
            function ($message) {
                $message->to(\auth()->user()->email, '')->subject
                ('Sneakers');
                $message->from(\auth()->user()->email, 'Sneakers');
            });

        Session::forget('carts');

        return redirect()->route('user.index');
    }

    public function delete (Request $request)
    {
        Session::forget('carts.' . $request->product_id);

        return redirect()->back();
    }
}

app/Http/Controllers/Site/CatalogController.php
<?php

namespace App\Http\Controllers\Site;

use App\Http\Controllers\Controller;
use App\Models\Product;
use App\Models\ShoeSize;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Storage;

class CatalogController extends Controller
{
    public function index(Request $request): \Illuminate\Contracts\View\View|\Illuminate\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\Foundation\Application
    {
        $products = Product::query()
            ->when(!is_null($request->product_id), fn(Builder $builder) => $builder->whereIn('id', $request->product_id))
            ->when(!is_null($request->min) && !is_null($request->max), fn(Builder $builder) => $builder->whereBetween('price', [$request->min, $request->max]))
            ->when(!is_null($request->sizes), function (Builder $builder) use ($request) {
                $builder->join('shoe_sizes', 'shoe_sizes.product_id', '=', 'products.id')
                    ->whereIn('shoe_sizes.size', $request->sizes);
            })
            ->when(!is_null($request->color), function (Builder $builder) use ($request) {
                $builder->join('shoe_colors', 'shoe_colors.product_id', '=', 'products.id')
                    ->whereIn('shoe_colors.color', $request->color);
            })
            ->when(!is_null($request->sort), fn(Builder $builder) => $builder->orderBy('price', 'asc'))
            ->select('products.*')
            ->groupBy('products.id')
            ->get();


        if (!empty($request->model)) {
            $products = Product::query()
                ->when(!is_null($request->model), fn(Builder $builder) => $builder->where('model', 'LIKE', '%' . $request->model . '%'))
                ->get();
        }


        $sizes = ShoeSize::query()
            ->orderBy('size')
            ->select('size')
            ->groupBy('size')
            ->get();

        return view('site.catalog.index', [
            'products' => $products ?? Product::all(),
            'sizes' => $sizes
        ]);
    }

    public function show(int $id): \Illuminate\Contracts\View\View|\Illuminate\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\Foundation\Application
    {
        $product = Product::query()->find($id);

        $images = Storage::allFiles('public/files/products/' . $product->id);
        $products = Product::query()->where('id', '<>', $id)->paginate(3);
        $sizes = ShoeSize::query()->where('product_id', '=', $id)
            ->orderBy('size')
            ->get();

        return view('site.catalog.show', [
            'product' => $product,
            'image_one' => Storage::url(Arr::first($images)),
            'image_two' => Storage::url($images[1] ?? null),
            'image_three' => Storage::url($images[2] ?? null),
            'products' => $products,
            'sizes' => $sizes
        ]);
    }

    public function filter (Request $request)
    {
        dd($request);
    }
}

app/Http/Controllers/Site/ContactController.php
<?php

namespace App\Http\Controllers\Site;

use App\Http\Controllers\Controller;
use App\Http\Requests\ContactRequest;
use App\Models\Contact;
use Illuminate\Http\Request;

class ContactController extends Controller
{
    public function index (): \Illuminate\Contracts\View\View|\Illuminate\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\Foundation\Application
    {
        return view('site.kontakts.kontakts');
    }

    public function store (ContactRequest $request): \Illuminate\Http\RedirectResponse
    {
        Contact::query()->create([
            'name' => $request->name,
            'email' => $request->email,
            'description' => $request->description,
            'phone' => $request->phone
        ]);

        return redirect()->back()->with('success', 'Спасибо что оставили ваши контакты');
    }
}

app/Http/Controllers/Site/MainController.php
<?php

namespace App\Http\Controllers\Site;

use App\Http\Controllers\Controller;
use App\Models\Product;
use App\Models\Review;
use Illuminate\Http\Request;

class MainController extends Controller
{
    public function index(): \Illuminate\Contracts\View\View|\Illuminate\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\Foundation\Application
    {
        return view('site.main.index', [
            'products' => Product::query()->paginate(4),
            'reviews' => Review::all()
        ]);
    }
}

resources/views/include/site/footer.blade.php
@if(in_array(request()->route()->getName(), ['busket.index', 'user.index', 'information']))
    <footer>
        <div class="coontainer">
            <div class="blocks">
                <div class="block-1">
                    <div class="top-text">Каталог</div>
                    <div class="mid-txt">
                        <a href="">Обувь</a>
                    </div>
                    <div class="mid-txt">
                        <a href="">Бренды</a>
                    </div>
                    <div class="mid-txt">
                        <a href="">Модели</a>
                    </div>
                    <div class="mid-txt">
                        <a href="">Информация</a>
                    </div>
                </div>
                <div class="block-2">
                    <div class="top-text">Информация</div>
                    <div class="mid-txt">
                        <a href="">Блог</a>
                    </div>
                    <div class="mid-txt">
                        <a href="">Контакты</a>
                    </div>
                    <div class="mid-txt">
                        <a href="">Доставка</a>
                    </div>
                    <div class="mid-txt">
                        <a href="">Оплата</a>
                    </div>
                </div>
                <div class="block-3">
                    <div class="top-text">Контакты</div>
                    <div class="mid-txt">
                        <a href="">vladstrok23@gmail.com</a>
                    </div>
                    <div class="mid-txt">
                        <a href="">+375445656947</a>
                    </div>
                    <div class="mid-txt">
                        <a href="">Месенджеры</a>
                        <div class="mes">
                            <a href="https://web.telegram.org/k/"><img src="{{asset('assets/image/snekers/tg.svg')}}" alt=""></a>
                            <a href=""><img src="{{asset('assets/image/snekers/tlf.svg')}}" alt=""></a>
                        </div>
                    </div>
                    <div class="mid-txt">
                        <a href="">Соц.сети</a>
                        <div class="mes">
                            <a href="https://vk.com/feed"><img src="{{asset('assets/image/snekers/vk.svg')}}" alt=""></a>
                            <a href="https://www.instagram.com/nnastten?igsh=MXhtM3U5YmI5bTVzZQ%3D%3D&utm_source=qr"><img src="{{asset('assets/image/snekers/inst.svg')}}" alt=""></a>
                        </div>

                    </div>
                </div>
                <div class="block-4"></div>
            </div>
            <div class="bot-block">
                <div class="prava">© Sneaker-Haven.bu, 2023 — 2025. Интернет - магазин продажи кросовок. Все права защищены.</div>
            </div>

        </div>
    </footer>
@else
    <footer>
        <div class="coontainer">
            <div class="block">
                <div class="block-1">
                    <div class="top-text">Каталог</div>
                    <div class="mid-txt">
                        <a href="">Обувь</a>
                    </div>
                    <div class="mid-txt">
                        <a href="">Бренды</a>
                    </div>
                    <div class="mid-txt">
                        <a href="">Расчет стоимости</a>
                    </div>
                    <div class="mid-txt">
                        <a href="">Информация</a>
                    </div>
                </div>
                <div class="block-2">
                    <div class="top-text">Информация</div>
                    <div class="mid-txt">
                        <a href="">Блог</a>
                    </div>
                    <div class="mid-txt">
                        <a href="">Контакты</a>
                    </div>
                    <div class="mid-txt">
                        <a href="">Доставка</a>
                    </div>
                    <div class="mid-txt">
                        <a href="">Оплата</a>
                    </div>
                </div>
                <div class="block-3">
                    <div class="top-text">Контакты</div>
                    <div class="mid-txt">
                        <a href="">vladstrok23@gmail.com</a>
                    </div>
                    <div class="mid-txt">
                        <a href="">+375445656947</a>
                    </div>
                    <div class="mid-txt">
                        <a href="">Месенджеры</a>
                        <div class="mes">
                            <a href="https://web.telegram.org/k/"><img src="{{asset('assets/image/snekers/tg.svg')}}" alt=""></a>
                            <a href=""><img src="{{asset('assets/image/snekers/tlf.svg')}}" alt=""></a>
                        </div>
                    </div>
                    <div class="mid-txt">
                        <a href="">Соц.сети</a>
                        <div class="mes">
                            <a href="https://vk.com/feed"><img src="{{asset('assets/image/snekers/vk.svg')}}" alt=""></a>
                            <a href="https://www.instagram.com/nnastten?igsh=MXhtM3U5YmI5bTVzZQ%3D%3D&utm_source=qr"><img src="{{asset('assets/image/snekers/inst.svg')}}" alt=""></a>
                        </div>

                    </div>
                </div>
                <div class="block-4"></div>
            </div>
            <div class="bot-block">
                <div class="prava">© Sneaker-Haven.bu, 2023 — 2025. Интернет - магазин продажи кросовок. Все права защищены.</div>
            </div>

        </div>
    </footer>
@endif

resources/views/include/site/header.blade.php
<header>
    <div class="header">
        <div class="logo">
            <a href="/"><img src="{{asset('assets/image/Group 362.svg')}}" alt=""></a></div>
        <nav class="one">
            <ul class="topmenu">
                <li>
                    <a href="/">Главная</a>
                </li>
                <li>
                    <a href="{{route('catalog.index')}}">Каталог</a>
                </li>
                <li><a href="{{route('blog')}}">Блог</a></li>
                <li><a href="{{route('contact.index')}}">Контакты</a></li>
                <li><a href="{{route('information')}}">Информация</a></li>
            </ul>
        </nav>
        <div class="burger-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                <path fill="white" fill-rule="evenodd" d="M3.5 5a1 1 0 0 0 0 2h17a1 1 0 1 0 0-2zm-1 7a1 1 0 0 1 1-1h17a1 1 0 1 1 0 2h-17a1 1 0 0 1-1-1m0 6.001a1 1 0 0 1 1-1h17a1 1 0 1 1 0 2h-17a1 1 0 0 1-1-1" clip-rule="evenodd" />
            </svg>
        </div>
        <div class="acaunts">
            @auth
                @if(auth()->user()->role_id == \App\Enum\Role\RoleEnum::USER->value)
                    <div class="brg"><img src="{{asset('assets/image/Vector (Stroke).sv')}}" alt=""></div>
                    <div class="name-users">{{auth()->user()->name}}</div>
                    <div class="ak">
                        <a href="{{route('user.index')}}"><img class="lk" src="{{asset('assets/image/header/ak.svg')}}"
                                                               alt=""></a>
                    </div>
                    <div class="pocup">
                        <a href="{{route('busket.index')}}">
                            <div class="sumka"><img class="lk" src="{{asset('assets/image/header/sumka.svg')}}" alt="">
                            </div>
                        </a>
                    </div>
                @else
                    <a href="{{route('admin.index')}}">Админ панель</a>
                @endif
            @else
                <a href="{{route('login.index')}}">Войти/Регистрация</a>
            @endauth
        </div>


    </div>
    <div class="burger-menu">
        <div class="closse-burg">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                <path fill="white" d="M6.4 19L5 17.6l5.6-5.6L5 6.4L6.4 5l5.6 5.6L17.6 5L19 6.4L13.4 12l5.6 5.6l-1.4 1.4l-5.6-5.6z" />
            </svg>
        </div>
        <div class="burger-menu-items">
            <ul class="burg-mens">
                <li>
                    <a href="/">Главная</a>
                </li>
                <li>
                    <a href="{{route('catalog.index')}}">Каталог</a>
                </li>
                <li><a href="{{route('blog')}}">Блог</a></li>
                <li><a href="{{route('contact.index')}}">Контакты</a></li>
                <li><a href="{{route('information')}}">Информация</a></li>
            </ul>
            <div class="acauntss">
                @auth
                    @if(auth()->user()->role_id == \App\Enum\Role\RoleEnum::USER->value)
                        <div class="brg"><img src="{{asset('assets/image/Vector (Stroke).sv')}}" alt=""></div>
                        <div class="name-users">{{auth()->user()->name}}</div>
                        <div class="ak">
                            <a href="{{route('user.index')}}"><img class="lk" src="{{asset('assets/image/header/ak.svg')}}"
                                                                   alt=""></a>
                        </div>
                        <div class="pocup">
                            <a href="{{route('busket.index')}}">
                                <div class="sumka"><img class="lk" src="{{asset('assets/image/header/sumka.svg')}}" alt="">
                                </div>
                            </a>
                        </div>
                    @else
                        <a href="{{route('admin.index')}}">Админ панель</a>
                    @endif
                @else
                    <a href="{{route('login.index')}}">Войти/Регистрация</a>
                @endauth
            </div>
        </div>
    </div>
</header>
<script>
    document.querySelector('.burger-icon').addEventListener('click', function() {
        document.querySelector('.burger-menu').style.display = 'block';
    })
    document.querySelector('.closse-burg').addEventListener('click', function() {
        document.querySelector('.burger-menu').style.display = 'none';
    })
</script>